### ISSUE TITLE
Export cleaned up Stats type

### ISSUE THREAD

**Issue by andrestc** [mdlayher/taskstats#1]
Creating this issue to track the TODO in https://github.com/mdlayher/taskstats/blob/master/stats_linux.go#L12. 

I plan addressing the delay accounting fields first, as I will use them in a CLI tool. Any specific implementation detail you want me to follow, @mdlayher? 

I'll open up a PR once I get something done.

**Comment by mdlayher** [comment]
Sounds like a plan to me. My biggest wants are giving these fields proper Go names, and if something is actually a duration or the like, using the proper Go type.

**Comment by mdlayher** [comment]
Oops, this was done! Thanks again.
