### ISSUE TITLE
README lacks a "Getting started" section

### ISSUE THREAD

**Issue by q2dg** [mdlayher/taskstats#4]
Sincerely, I don't know how to begin using this tool.
Thanks

**Comment by mdlayher** [comment]
I'm honestly not sure what would help. It's a package to access the Linux's taskstats API. You create a Client and call its methods to fetch data. That's about it.

What kind of information are you looking for?

**Comment by q2dg** [comment]
Ok, so it's a library, not a command-line tool, right? I misunderstood, sorry

**Comment by mdlayher** [comment]
Yep, it's a package that could be used to build a CLI tool, but one is not included at the moment. No worries!
